"""Typed configuration for the whole distillation lifecycle, loadable from YAML recipes."""

from __future__ import annotations

from pathlib import Path
from typing import Literal, Optional

import yaml
from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict, Field


class BaseModel(PydanticBaseModel):
    # Reject unknown fields everywhere: a typo'd recipe key (or a bogus field in
    # an API request to the web UI) fails loudly instead of being ignored.
    model_config = ConfigDict(extra="forbid")


class TeacherConfig(BaseModel):
    """Where knowledge comes from.

    ``spec`` selects the backend:
      - ``hf:<repo_or_path>``     local HF model (white-box: logits available)
      - ``claude`` / ``claude:<model>``  Anthropic API (black-box)
      - ``openai:<model>``        OpenAI API (black-box)
      - ``ollama:<model>``        local Ollama server (black-box)
    """

    spec: str = "hf:HuggingFaceTB/SmolLM2-360M-Instruct"
    system: Optional[str] = None
    max_tokens: int = 512
    concurrency: int = 4  # parallel requests for API teachers


class LoraSettings(BaseModel):
    """LoRA adapter training: freeze the base model, train small low-rank adapters.

    This is what makes 1-3B students practical on a 16GB laptop — no optimizer
    state or gradients for the base weights. ``qlora: true`` additionally loads
    the frozen base in 4-bit NF4 (CUDA only; bitsandbytes has no MPS backend).
    Requires: pip install "distill-anything[lora]"
    """

    r: int = 16
    alpha: int = 32
    dropout: float = 0.05
    # None = let peft pick the projection layers for known architectures.
    target_modules: Optional[list[str]] = None
    qlora: bool = False


class StudentConfig(BaseModel):
    model: str = "HuggingFaceTB/SmolLM2-135M-Instruct"
    trust_remote_code: bool = False
    lora: Optional[LoraSettings] = None


class DataConfig(BaseModel):
    """Training data. JSONL records may be:

    ``{"prompt": ..., "response": ...}`` | ``{"text": ...}`` | ``{"messages": [...]}``.
    ``.txt`` files are read as one prompt per line (responses generated by the teacher).
    """

    path: str = "data/train.jsonl"
    max_seq_len: int = 512
    eval_fraction: float = 0.05
    max_records: Optional[int] = None
    dedup: bool = True
    min_response_chars: int = 1


class LossConfig(BaseModel):
    kind: Literal["forward_kl", "reverse_kl", "jsd"] = "forward_kl"
    temperature: float = 2.0
    # total = alpha * KD + (1 - alpha) * CE. alpha=0 is plain SFT.
    alpha: float = 0.5
    # Truncate KD to the teacher's top-k logits (memory saver on small devices).
    top_k: Optional[int] = None
    jsd_beta: float = 0.5


class TrainConfig(BaseModel):
    output_dir: str = "runs/distilled"
    lr: float = 1e-4
    epochs: int = 1
    max_steps: Optional[int] = None
    batch_size: int = 2
    grad_accum: int = 4
    warmup_ratio: float = 0.03
    weight_decay: float = 0.01
    grad_clip: float = 1.0
    seed: int = 42
    log_every: int = 10
    eval_every: Optional[int] = None  # steps; None = eval at end only
    # Trade compute for memory — recompute activations in backward. Recommended
    # for LoRA students >= 1B on laptops.
    gradient_checkpointing: bool = False
    # After LoRA training, merge adapters into the base so output_dir is a plain
    # HF checkpoint. Set False to save only the (tiny) adapters. QLoRA never merges.
    merge_lora: bool = True


class DistillConfig(BaseModel):
    """A full recipe: mode + teacher + student + data + loss + training."""

    # logit  = white-box KD (teacher runs locally, KL on logits)
    # seqkd  = black-box KD (train on teacher-generated text; CE only)
    mode: Literal["logit", "seqkd"] = "logit"
    teacher: TeacherConfig = Field(default_factory=TeacherConfig)
    student: StudentConfig = Field(default_factory=StudentConfig)
    data: DataConfig = Field(default_factory=DataConfig)
    loss: LossConfig = Field(default_factory=LossConfig)
    train: TrainConfig = Field(default_factory=TrainConfig)

    @classmethod
    def from_yaml(cls, path: str | Path) -> "DistillConfig":
        with open(path) as f:
            raw = yaml.safe_load(f) or {}
        return cls.model_validate(raw)

    def to_yaml(self, path: str | Path) -> None:
        with open(path, "w") as f:
            yaml.safe_dump(self.model_dump(), f, sort_keys=False)
